#!/usr/bin/env bash
#This script displays "Best School" 9 times and Hi on a new line

x=1

while [ $x -lt 10 ]

do
    echo "Best School"
    if [ $x -gt 9 ]
    then
	echo "Hi"
    fi
    ((x++))
done
