#!/usr/bin/env bash

#This scripts displays the content of the current directory in a list format

#where only the part of the name after the first dash is displayed

#Only the for loop must be used

#No hidden files displayed



mylist=$(ls)



for i in $mylist;

do

    echo "$i" | cut -d '-' -f2

done
